language: minimal
before_script:
  - curl -fsSL https://deno.land/x/install/install.sh | sh
script:
  - /home/travis/.local/bin/deno test --allow-net test.ts
  - /home/travis/.local/bin/deno example.ts
